services:
  postgres:
    image: postgres:13
    container_name: postgres
    volumes:
      # This volume persists the Postgres data
      - ./.postgres_data:/var/lib/postgresql/data

      # Place your schema file(s) here so Postgres runs them on container initialization.
      # All SQL files inside /docker-entrypoint-initdb.d run exactly once if no database is initialized.
      - ./initdb:/docker-entrypoint-initdb.d

    ports:
      - "5432:5432"